export default {
  PLACE_CARD: 'PLACE_CARD',
  LIST_CARD_SMALL: 'LIST_CARD_SMALL',
  LIST_CARD_BIG: 'LIST_CARD_BIG',
  THREE_PICTURES: 'THREE_PICTURES',
  TWO_PICTURES: 'TWO_PICTURES',
  FOUR_PICTURES: 'FOUR_PICTURES',
};
