import Colors from './Colors';

export default {
  borderRadiusCardContainer: 35,
  borderRadiusCard: 20,
  borderRadiusRoundButton: 40,
  fontSizeScreenTitle: 33,
  iconSize: 24,
  inputIconSize: 18,
  fontSize: {
    h1: 30,
    h2: 28,
    h3: 24,
    h4: 20,
    h5: 18,
    h6: 16,
    h7: 14,
    h8: 12,
  },
  marginTopCardContainer: 10,
  paddingCardContainer: 5,
  marginCard: 7,
  marginSmallCard: 4,
  marginTextInput: 5,
  paddingCard: 10,
  paddingTextInputContent: 15,
  paddingTextInput: 5,
  inputStyle: {
    padding: 12,
    marginBottom: 15,
    backgroundColor: Colors.inputBackgroundColor,
    borderColor: Colors.inputBackgroundColor,
    borderWidth: 0,
    borderRadius: 20,
  },
  shadow: {
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 5,
    elevation: 6,
  },
};
